In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
from google.colab import files
uploaded = files.upload()

Saving gaitocamera.csv to gaitocamera (1).csv
Saving population.csv to population (2).csv
Saving traffic.csv to traffic (1).csv

In [0]:
df01 = pd.read_csv('population.csv', encoding='shift-jis', header=5)
df02 = pd.read_csv('gaitocamera.csv', encoding='shift-jis')
df03 = pd.read_csv('traffic.csv', encoding='shift-jis')

**東京都男女年齢(５歳階級)別人口の予測**

In [24]:
df01.tail(5)

     6  地域別階層コード 地域識別コード  地域コード    地域名  2015  2020  2025  2030  2035  2040
67  74         3       d  13400   八丈支庁  7791  7076  6417  5868  5430  5006
68  75         4       3  13401    八丈町  7613  6890  6244  5701  5272  4851
69  76         4       3  13402   青ヶ島村   178   186   173   167   158   155
70  77         3       d  13420  小笠原支庁  3022  3180  3259  3258  3232  3169
71  78         4       3  13421   小笠原村  3022  3180  3259  3258  3232  3169

**街頭防犯カメラシステム整備地区の刑法犯認知件数**

In [25]:
df02.tail(5)

,地区,運用開始日,平成１３年,平成１３年路上犯罪の認知件数,平成１４年,平成１４年路上犯罪の認知件数,平成１５年,平成１５年路上犯罪の認知件数,平成１６年,平成１６年路上犯罪の認知件数,...,平成２５年,平成２５年路上犯罪の認知件数,平成２６年,平成２６年路上犯罪の認知件数,平成２７年,平成２７年路上犯罪の認知件数,平成２８年,平成２８年路上犯罪の認知件数,平成２9年,平成２9年路上犯罪の認知件数
1,渋谷,平成１６年３月２２日から,NaN,NaN,NaN,NaN,2802.0,509.0,2330.0,483.0,...,1303,275,1380,279,1359,284,1080,279,1082,264
2,池袋,平成１６年３月２４日から,NaN,NaN,NaN,NaN,3244.0,1121.0,2941.0,1015.0,...,1649,381,1579,328,1476,301,1197,279,1270,271
3,上野２丁目,平成１８年２月１５日から,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,427,144,321,104,295,92,251,82,206,61
4,六本木,平成１９年３月２０日から,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,956,230,946,257,808,247,677,179,630,143
5,錦糸町,平成２５年３月２３日から,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,448,138,495,160,494,136,408,107,399,92

**平成27年度　全国道路交通情報調査道路交通センサス **

In [26]:
df03.tail(5)

,道路種別調査実施機関,区部高速自動車国道平日,区部高速自動車国道平日２４時間,区部高速自動車国道休日,区部高速自動車国道休日24時間,区部都市高速道路平日,区部都市高速道路平日２４時間,区部都市高速道路休日,区部都市高速道路休日24時間,区部一般国道自動車専用道路平日,...,市郡部都道一般都道休日,市郡部都道一般都道休日24時間,市郡部計平日,市郡部計平日２４時間,市郡部計休日,市郡部計休日24時間,合計平日,平日２４時間,合計休日,合計休日24時間
1,中日本高速道路株式会社,5.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28,28,28,28,33,33,33,33
2,首都高速道路株式会社,NaN,NaN,NaN,NaN,138.0,138.0,0.0,0.0,NaN,...,NaN,NaN,0,0,0,0,138,138,0,0
3,国土交通省関東地方整備局,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,174,19,0,0,461,86,0,0
4,東京都建設局,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43.0,0.0,128,5,65,1,210,12,65,1
5,合計,8.0,8.0,8.0,8.0,138.0,138.0,0.0,0.0,3.0,...,43.0,0.0,335,57,98,34,855,282,111,47